### ISSUE TITLE
Переписать на typescript

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/vsc-language-1c-bsl#10]
Частично переопределил f12 и поиск ссылок, если работаем не  с файлом, а с каталогом.
http://screencast.com/t/XLIa3dQ7rvn1

Аналогично и подстановка подсказок для общих модулей http://screencast.com/t/1cUEXVd4T6r

**Comment by nixel2007** [comment]
@pumbaEO очень круто! можешь поделиться кодом? надеюсь портировать для Атома, если получится.

**Comment by nixel2007** [comment]
А зачем переписывать на typescript?

**Comment by pumbaEO** [comment]
я просто взял существующий плагин для с++ с использованием gtags, добавил туда парсинг модулей 1с и при доработки филтрации в автокомлите, понял, что в typescript удобней дорабатывать код, чем в чистом javascript , типизация рулит.

**Comment by pumbaEO** [comment]
Случайно запушил в ветку autocomplitefilter, порт на typescript  https://github.com/pumbaEO/vsc-language-1c-bsl/tree/feature/autocomplitefilter 
Вроде все кроме линтера работает.

**Comment by nixel2007** [comment]
@pumbaEO правильно понимаю, что ты разделил все провайдеры на отдельные файлы?

Не нашел сходу добавленную команду `onCommand:bsl.update` - где она и для чего? :)

**Comment by pumbaEO** [comment]
Да, каждый провайдер на отдельный файл. 
bsl.update нужна для обновление кэша экспортных процедур, т.к. например для erp это занимает секунд 40 обойти все файлы, то просто добавил как отдельную команду, для ручного обновления при необходимости https://github.com/pumbaEO/vsc-language-1c-bsl/blob/feature/autocomplitefilter/src/extension.ts#L29

**Comment by nixel2007** [comment]
Реализовано.
