### ISSUE TITLE
lint под linux не работает, т.к. необходимо указывать команду mono oscript 

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/vsc-language-1c-bsl#12]
Под linux комманда oscript не отрабатывает, т.к. необходимо указывать в строке запуска mono oscript.exe

**Comment by nixel2007** [comment]
Под линукс разве нет нативного бинарника? 
@EvilBeaver

**Comment by pumbaEO** [comment]
Есть, там чуть сложнее надо или же делать свой скрипт запускалку, но т.к. у Андрея сборка делается под виндой и архив zip то там права на запуск не устанавливаются, что-бы нативно в linux поддерживать. 
Поэтому я чуть доработал запуск, т.е. когда вызывается процесс, то запускается mono и в параметрах передается путь к oscript

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #102](https://github.com/xDrivenDevelopment/1c-syntax/issues/102) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by nixel2007** [comment]
Перенес в основной репо, так как проблема общая для всех редакторов
