### ISSUE TITLE
автоматическое закрытие скобки

### ISSUE THREAD

**Issue by alarcl** [xDrivenDevelopment/vsc-language-1c-bsl#24]
После выбора вашего типа файла (1C-BCL) во всех вкладках и во вновь открытых файлах, не зависимо от типа файла, после символа `( `автоматически вставляется символ `)`.
Версия VSCode 1.7.1.

**Comment by nixel2007** [comment]
Насколько я понимаю, это в свете вот этой проблемы https://github.com/Microsoft/vscode/issues/15625

Действительно, мы не учитываем данную настройку. Спасибо за баг-репорт. 
/cc @bambr1975

**Comment by nixel2007** [comment]
Перенёс в основной репозиторий 1c-syntax https://github.com/xDrivenDevelopment/1c-syntax/issues/229
