### ISSUE TITLE
definitionProvider

### ISSUE THREAD

**Issue by buzzzzer** [xDrivenDevelopment/vsc-language-1c-bsl#29]
В class GlobalDefinitionProvider
вот тут:
```
if (this._global.globalfunctions[wordAtPosition.toLowerCase()]) {
                return undefined;
}
```
return наверно нужно поменять на 
```
Promise.resolve(undefined);
```

**Comment by nixel2007** [comment]
По хорошему да. А что, приводит к каким-то ошибкам?

**Comment by buzzzzer** [comment]
Да. Если навестись мышой с контролом на функцию которая есть в globalfunctions, то потом отстальные не подчеркиваются при контроле, хотя переходы всё равно работают

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #241](https://github.com/xDrivenDevelopment/1c-syntax/issues/241) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #242](https://github.com/xDrivenDevelopment/1c-syntax/issues/242) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nixel2007** [comment]
Спасибо за багрепорт, перенес в основной репо
