### ISSUE TITLE
Как работать со стандартными файлами конфигурации?

### ISSUE THREAD

**Issue by a-a-k** [xDrivenDevelopment/vsc-language-1c-bsl#39]
Недавно начал знакомиться с 1С, не очень понятно как редактировать код в файлах `.epf` например.  Что за расширение .`os`?

**Comment by nixel2007** [comment]
EPF - это бинарный формат хранения, его невозможно редактировать в текстовом редакторе. Для редактирования кода внешних обработок их необходимо предварительно выгрузить в файлы из конфигуратора.
os - расширение скриптов движка oscript.io

P.S. Просьба создавать issue в репозитории https://github.com/xDrivenDevelopment/1c-syntax.

**Comment by AlexStrizh** [comment]
.os - это расширение OneScript (http://oscript.io)
.epf - это расширение внешней обработки 1С, там она используется и редактируется.

**Comment by a-a-k** [comment]
@nixel2007 Есть подробная информация? Где почитать? 

> Для редактирования кода внешних обработок их необходимо предварительно выгрузить в файлы из конфигуратора.

**Comment by nixel2007** [comment]
http://its.1c.ru/db/v838doc#bookmark:dev:TI000000332
http://its.1c.ru/db/v838doc#bookmark:adm:TI000000669

**Comment by a-a-k** [comment]
Увы, нет итс.

**Comment by AlexStrizh** [comment]
Можете цель хоть написать, зачем вам править внешнюю обработку в OneScript, если обработки нужны для платформы 1С?

**Comment by a-a-k** [comment]
@AlexStrizh Мне нужен редактор кода.

**Comment by nixel2007** [comment]
Почему не использовать для этого Конфигуратор?

**Comment by AlexStrizh** [comment]
Вы не сможете править код EPF в редакторе кода.

**Comment by nixel2007** [comment]
В всц можно редактировать конфигурации и внешние обработки (в исходниках), но для этого нужен набор технических знаний и соответствующий инструментарий. Можете начать с вебинара Евгения Сосны на инфостарте

**Comment by a-a-k** [comment]
> Почему не использовать для этого Конфигуратор?
Привык к студии, конфигуратор ломает меня.

> Можете начать с вебинара Евгения Сосны на инфостарте
Ссылочку плиз

**Comment by AlexStrizh** [comment]
@a-a-k Вы не сможете редактировать EPF для использования его в рамках 1С:Предприятия с помощью редактора кода, так как это бинарник (!).  С помощью OneScript мы его разбираем на исходники для иных целей, например, для git. Если вас попросили поправить что-то во внешней обработки и вы решили использовать привычный вам инструмент, то вы не на верном пути. Это делать надо в Конфигураторе.

**Comment by nixel2007** [comment]
> Привык к студии, конфигуратор ломает меня.

Придется сломаться. Вы объективно не сможете создавать объекты метаданных, рисовать формы, работать с различными конструкторами (коих не один десяток) из всц - они банально не реализованы и к реализации не планируются. не говоря уже о том, что это безумно трудозатратно.

Может быть вам будет ближе EDT (решение для 1с на базе eclipse), но оно пока еще в глубокой бете, нестабильно и не предоставляет всей функциональности конфигуратора (в том числе по объектам метаданных), так что все равно надо будет работать в конфигураторе.

Вебинар - http://infostart.ru/webinars/564263/

**Comment by nixel2007** [comment]
@AlexStrizh 
> С помощью OneScript мы его разбираем на исходники для иных целей, например, для git. 

внешние обработки начиная с 8.3.8 имеют нативную загрузку и выгрузку в исходники. Так что такой сценарий использования вполне возможен. Ровно до тех пор, пока нет необходимости править метаданные обработки или ее формы.

**Comment by AlexStrizh** [comment]
Я привел это для примера. Человек явно не на том пути.

**Comment by a-a-k** [comment]
@nixel2007 спасибо, с формами и прочим нет проблем работать и в конфигураторе, но их редактор кода меня не устраивает. Мне нужно решение именно для разделённой разработки - код в отдельном редакторе, объекты в конфигураторе. Если это возможно, то это решает мою проблему. Поэтому решил испробовать этот вариант, если не подойдёт - ну буду ломаться.

@AlexStrizh позвольте мне самому выбирать путь и решать тот он или нет.

**Comment by AlexStrizh** [comment]
Не позволю.

**Comment by nixel2007** [comment]
@AlexStrizh кхм.

**Comment by AlexStrizh** [comment]
@nixel2007 ибо нефиг.
