### ISSUE TITLE
Дублирование точки при автокомплите

### ISSUE THREAD

**Issue by a-a-k** [xDrivenDevelopment/vsc-language-1c-bsl#40]
На примере - автокомплит для Справочники со сниппетом цикла.
[Ссылка на видео](http://take.ms/3Rl3K)

**Comment by nixel2007** [comment]
Это не дублирование точки - вам надо написать имя справочника, из которого происходит выборка :)

**Comment by AlexStrizh** [comment]
Все правильно работает, Ознакомьтесь с самим языком 1С, чтобы понимать к чему это всё и зачем. Например, http://v8.1c.ru/metod/books/book.jsp?id=401
