### ISSUE TITLE
Области не сворачиваются

### ISSUE THREAD

**Issue by Faithfinder** [xDrivenDevelopment/vsc-language-1c-bsl#52]
Сабж.
#Область Чтонибудь
Должно сворачиваться
#КонецОбласти

**Comment by nixel2007** [comment]
Настройки сворачиваемых областей нет в редакторе.
Есть старая задача https://github.com/xDrivenDevelopment/1c-syntax/issues/30, но в силу ограничений движка на данный момент единственная возможность свернуть область - отделять весь код в ней табуляцией.
