### ISSUE TITLE
Symbols provider

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/vsc-language-1c-bsl#7]
Когда используется перенос строки LF, SymbolsProvider неправильно выдает указатель на символы.
![screenshot 2016-02-24 11 58 22](https://cloud.githubusercontent.com/assets/8318227/13279025/154d7cc0-daee-11e5-867a-d7fd560ee82b.png)

**Comment by nixel2007** [comment]
Спасибо за репорт, исправим.

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #97](https://github.com/xDrivenDevelopment/1c-syntax/issues/97) via [**ZenHub.io**](https://www.zenhub.io/)
