### ISSUE TITLE
Неправильно определяет файл для подчеркивания красным

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/vsc-language-1c-bsl#74]
* Заходим в packman (на момент написания актуальный коммит https://github.com/oscript-library/packman/commit/52bd1bffcc6ab13971cb8bfccd9ecd1d4507428f)
* Открываем файл src\Классы\КомандаПроверитьСинтаксис.os
* Делаем в нем что-то, чтобы сработал линтер и видим в строке 40 красную черту и текст "Недостаточно фактических параметров", что неверно
* Если запустить oscript с ключом check и правильной точкой входа, то увидим, что ошибка реально есть, но в файле src\Классы\КомандаСоздатьДистрибутив.os

Т.е. линтер неправильно определил файл, в котором надо подчеркнуть чертой.

**Comment by EvilBeaver** [comment]
Канеш. Иначе было бы совсем другое.

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #278](https://github.com/xDrivenDevelopment/1c-syntax/issues/278) via [**ZenHub**](https://www.zenhub.com/)
