### ISSUE TITLE
Информация по настройке устарела

### ISSUE THREAD

**Issue by jafariuse** [xDrivenDevelopment/vsc-language-1c-bsl#80]
Информация по настройке запуска .os в Visual Studio Code не корректна для текущей версии Visual Studio Code (1,17.2)
В частности: 
- отсутствует команда Language 1C (BSL): Create tasks.json for current workspace
- файл tasks.json должен формироваться по новым правилам ( "version": "2.0.0"):
* Свойство isShellCommand является устаревшим
* Свойство showOutput является устаревшим
* Свойство showOutput является устаревшим. 
* Свойство suppressTaskName является устаревшим
* Свойство isBuildCommand является устаревшим. 
* Свойство echoCommand является устаревшим
необходимо обновить иструкцию

**Comment by bambr1975** [comment]
В информации о релизе https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/releases/tag/v1.10.0 указано:
>Переработана работа с тасками - новое API от VSCode позволило избавится от необходимости создания tasks.json для запуска простейших задач.

В общем и целом, работа с тасками сейчас полностью соответствует https://code.visualstudio.com/docs/editor/tasks

Страницу https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B2-.os-.bsl-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-OneScript действительно наверное, можно просто удалить, оставив ссылку на https://code.visualstudio.com/docs/editor/tasks .
Что касается нового варианта возможной инструкции, то она простая:
Теперь, находясь в открытом os-файле достаточно просто нажать F1 - выбрать команду "Задачи:Выполнить задачу" (или даже сразу нажать комбинацию Ctrl+Shift+B, если нужно выполнить задачу запуска os-файла) и будет выведен выпадающий список, где доступны все основные команды запуска и обработки os-файлов
P.S. Есть тонкость - в каталоге .vscode открытой папки не должно содержаться файла task.json, где в качестве версии указана версия 0.1.0 - в этом случае новое API не срабатывает и отрабатывают задачи, указанные в файле task.json.
P.P.S. Более подробно о новом TasksApi VSCode можно прочитать по ссылке https://code.visualstudio.com/docs/editor/tasks

**Comment by artbear** [comment]
Доку нужно исправить, ишуз сейчас переоткрыть и закрыть только после
исправления доки

26 Окт 2017 г. 9:53 пользователь "jafariuse" <notifications@github.com>
написал:

Closed #80
<https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/issues/80>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/issues/80#event-1311318311>,
or mute the thread

**Comment by bambr1975** [comment]
ждем @nixel2007  . Он главный по доке )))

**Comment by bambr1975** [comment]
https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B2-.os-.bsl-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-OneScript

**Comment by artbear** [comment]
А мне @nixel2007 подсказал, что если есть скрипты-таски для opm в каталоге tasks, то они также подхватятся в таски VSC.
@bambr1975 Добавишь в доку?

PS я сам не добавляю, потому что я не уверен, что я правильно сформулирую

**Comment by bambr1975** [comment]
ммм. Заголовок доки - Запуск скриптов .os .bsl с помощью OneScript. Переименовать?

**Comment by artbear** [comment]
Да, лучше переименовать

**Comment by nixel2007** [comment]
Если ссылка поменяется и не будет редиректа - то не надо переименовывать. Ссылка разлетелась уже.

**Comment by artbear** [comment]
@bambr1975 Внесла изменения, я отревьюил, все в порядке.
Как всегда, в сторону @bambr1975 идут лучи добра за оперативность и качество :)
