### ISSUE TITLE
Ошибка 'package-def' of null: TypeError

### ISSUE THREAD

**Issue by petypen** [xDrivenDevelopment/vsc-language-1c-bsl#82]
В средствах разработчика ошибка. Возникает сразу при открытии VSC. Работать вроде бы не мешает.
Скриншот и лог во вложении
![2017-11-14 15-08-23 test os - relisemaker_3 - visual studio code](https://user-images.githubusercontent.com/6500075/32779175-c0a75088-c94d-11e7-8d52-bebbb81ac875.png)
[20171114.log](https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/files/1470681/20171114.log)

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #284](https://github.com/xDrivenDevelopment/1c-syntax/issues/284) via [**ZenHub**](https://www.zenhub.com/)
