### ISSUE TITLE
Линтер чувствителен к имени файла скрипта 

### ISSUE THREAD

**Issue by petypen** [xDrivenDevelopment/vsc-language-1c-bsl#83]
Если имя файла скрипта набрано большими буквами, то линтер не подчеркивает ошибки.
![2017-11-14 14-57-50 rm3 os - relisemaker_3 - visual studio code](https://user-images.githubusercontent.com/6500075/32779254-0c9b1574-c94e-11e7-8325-45d86e50a578.png)
![2017-11-14 14-58-28 rm3 os - relisemaker_3 - visual studio code](https://user-images.githubusercontent.com/6500075/32779263-11be337e-c94e-11e7-838d-9000c070b76c.png)

**Comment by nixel2007** [comment]
Issue moved to [xDrivenDevelopment/1c-syntax #285](https://github.com/xDrivenDevelopment/1c-syntax/issues/285) via [**ZenHub**](https://www.zenhub.com/)
